services:
  caddy:
    image: caddy:2
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    ports:
      - '80:80'
      - '443:443'
      - '443:443/udp'
    volumes:
      - $PWD/conf:/etc/caddy
      - $PWD/dist:/srv
      - caddy_data:/data
      - caddy_config:/config
  dev:
    build:
      context: .
    ports:
      - "4321:4321"
    volumes:
      - .:/app
      - /app/node_modules
    command: npx astro dev --host 0.0.0.0
    environment: 
      - NODE_ENV=development

volumes:
  caddy_data:
  caddy_config:
